// grab the user model
var express = require('express');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
var hash = require('./passEncryption').hash;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
var bodyParser = require('body-parser');  
var cookieParser = require('cookie-parser');
var session = require('express-session');
var mongoose = require("mongoose");

var User = require('../Models/User');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
var app = express();  
     

// config                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// middleware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

app.use(bodyParser.json());                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
app.use(cookieParser());                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

app.use(session({

  genid: function(req) {
    return guid(); // use UUIDs for session IDs 
  },
  secret: 'asavadv'

}
));

app.use(function(req,res,next) {
	console.log("Request.url: ", req.originalUrl);
	console.log("==================Got request body: ");
	console.log(req.body);
	console.log("Method: ", req.method);
	next();
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// Session-persisted message middleware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// app.use(function(req, res, next){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
//   var err = req.session.error                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
//     , msg = req.session.success;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
//   delete req.session.error;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
//   delete req.session.success;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
//   next();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
// });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// dummy database                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// when you create a user, generate a salt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
// and hash the password ('foobar' is the pass here)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// hash('foobar', function(err, salt, hash){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
//   if (err) throw err;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
//   // store the salt & hash in the "db"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
//   users.tj.salt = salt;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
//   users.tj.hash = hash.toString();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
// });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
// Authenticate using our plain-object database of doom!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
function authenticate(name, pass, fn) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  if (!module.parent) 
  	console.log('authenticating %s:%s', name, pass);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  
	User.find({ username: name }, function(err, userFromDatabase) {
  							if (err) 
  								{
  									return null;
  								}
  								else if (userFromDatabase != null)
							  	{
  									console.log("Got user: ", userFromDatabase);
							  		
							  		hash(pass, userFromDatabase[0].salt.toString(), function(err, hash){
							  		console.log("Got hash: ", hash.toString('hex'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
								    
								    if (err) 
								    	return fn(err);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
								    
								    if (hash.toString() == userFromDatabase[0].hash) 
								    	return fn(null, userFromDatabase[0]); 

								    fn(new Error('invalid password'));
							  		});
							  	}
								else
								{ 
							  		return fn(new Error('cannot find user'));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
							  	}
		});

  	
  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
function restrict(req, res, next) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  if (req.session.user) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    next();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  } else {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    req.session.error = 'Access denied!';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    res.redirect('/login');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
}    


app.get('/restricted', restrict, function(req, res){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  res.send('Wahoo! restricted area, click to <a href="/logout">logout</a>');                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
app.get('/logout', function(req, res){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  // destroy the user's session to log them out                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
  // will be re-created next request                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  req.session.destroy(function(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    res.redirect('/');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
app.get('/login', function(req, res){  
console.log("Got req: "+req.originalUrl+", method: "+req.method);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  res.render('login');                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
app.post('/login', function(req, res){
  authenticate(req.body.username, req.body.password, function(err, user){                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    var jsonResult;

    if (user) 
    {  
    	jsonResult = {"exit_code": 1, "message":""};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        
        // Regenerate session when signing in                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        // to prevent fixation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        req.session.regenerate(function(){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        
        // Store the user's primary key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        // in the session store to be retrieved,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        // or in this case the entire user object                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        req.session.user = user._id; 
        res.end(JSON.stringify(jsonResult));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    } 
    else 
    {  
    	var jsonResult = {"exit_code": 0, "message": err};                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      	req.session.error = 'Authentication failed. ' + err;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        console.log("We're in here, there was an error in authenticating the user");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        res.end(JSON.stringify(jsonResult));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
  });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
});       

app.post('/signup', function(req, res){
	User.find({ username: req.body.username }, function(err, userFromDatabase) {
  							
  							if (err) 
  								{
  									console.log("Got user: ", err);
  									return null;
  								};

  							if (userFromDatabase == null)
							{
								console.log("Got user: ", userFromDatabase);
								var randomSalt = Math.floor(Math.random() * 9000) + 1000;
							  	hash(req.body.password, randomSalt.toString() ,function(err, hash){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

								    var newUser =  new User({
										 _id : mongoose.Types.ObjectId(),
										  username : req.body.username,
										  password : hash,
										  creation_date : Date.now,
										  email : req.body.email,
										  address: req.body.address,
										  salt : randomSalt
										});  

									newUser.save(function(err) {
									  	if (err) throw err;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
										});
								});
							}});
  	
});                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                          

 function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
    s4() + '-' + s4() + s4() + s4();
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
app.listen(80);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
console.log('Express started on port ' + 80); 